[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"
bytecode_hash = "none"
gas_reports = ["Wallet"]
fs_permissions = [{ access = "read", path = "./"}]

# Super-optimized for gas snapshots / comparisons
[profile.gas]
optimizer = true
optimizer_runs = 10000
via_ir = true
evm_version = "paris"
gas_reports = ["Wallet"]

# CI: stricter, fail on warnings
[profile.ci]
deny_warnings = true
optimizer = true
optimizer_runs = 500
via_ir = false

# Try an older compiler to see changes (for experimentation)
[profile.oldsol]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Formatter options are placed in a separate file (.forgefmt.toml)
